services:
  db:
    image: postgres
    container_name: meal_list_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: meallistdb
    ports:
      - "5432:5432"
    volumes:
      - meal_list_pgdata:/var/lib/postgresql/data
volumes:
  meal_list_pgdata: