// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleStandard Role = "standard"
	RoleAdmin    Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type UnitCategory string

const (
	UnitCategoryMass   UnitCategory = "mass"
	UnitCategoryVolume UnitCategory = "volume"
	UnitCategoryCount  UnitCategory = "count"
)

func (e *UnitCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitCategory(s)
	case string:
		*e = UnitCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitCategory: %T", src)
	}
	return nil
}

type NullUnitCategory struct {
	UnitCategory UnitCategory
	Valid        bool // Valid is true if UnitCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitCategory) Scan(value interface{}) error {
	if value == nil {
		ns.UnitCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitCategory), nil
}

type CustomListItem struct {
	CustomListItemID       int32
	CustomListItemName     pgtype.Text
	CustomListItemQuantity pgtype.Float4
	CustomUnit             pgtype.Text
	UnitID                 pgtype.Int4
}

type Ingredient struct {
	IngredientID   int32
	IngredientName string
	UnitID         pgtype.Int4
}

type IngredientCategory struct {
	IngredientCategoryID   int32
	IngredientCategoryName string
}

type IngredientsToCategory struct {
	IngredientToCategoryID int32
	IngredientID           int32
	CategoryID             int32
}

type List struct {
	ListID    int32
	ListName  pgtype.Text
	UserID    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ListItem struct {
	ListItemID       int32
	ListID           int32
	IngredientID     pgtype.Int4
	CustomListItemID pgtype.Int4
}

type ListsToRecipe struct {
	ListID             int32
	RecipeID           int32
	ListRecipeQuantity float32
}

type Recipe struct {
	RecipeID      int32
	RecipeName    string
	Directions    string
	SourceUrl     pgtype.Text
	ImageFilename string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type RecipeCategory struct {
	RecipeCategoryID   int32
	RecipeCategoryName string
}

type RecipesToIngredient struct {
	RecipeID                 int32
	IngredientID             int32
	RecipeIngredientQuantity float32
}

type RecipesToRecipeCategory struct {
	RecipeToRecipeCategoryID int32
	RecipeID                 int32
	RecipeCategoryID         int32
}

type Unit struct {
	UnitID           int32
	UnitName         string
	ConversionFactor float32
	UnitCategory     NullUnitCategory
}

type User struct {
	UserID       int32
	Username     string
	PasswordHash string
	Role         Role
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserSession struct {
	SessionID  string
	UserID     int32
	LastAccess pgtype.Timestamp
}
