// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToListRecipeQuantity = `-- name: AddToListRecipeQuantity :exec
update lists_to_recipes set list_recipe_quantity = list_recipe_quantity + $3 where list_id = $1 and recipe_id = $2
`

type AddToListRecipeQuantityParams struct {
	ListID             int32
	RecipeID           int32
	ListRecipeQuantity float32
}

func (q *Queries) AddToListRecipeQuantity(ctx context.Context, arg AddToListRecipeQuantityParams) error {
	_, err := q.db.Exec(ctx, addToListRecipeQuantity, arg.ListID, arg.RecipeID, arg.ListRecipeQuantity)
	return err
}

const createIngredient = `-- name: CreateIngredient :one
insert into ingredients (ingredient_name) values ($1) returning ingredient_id, ingredient_name, unit_id
`

func (q *Queries) CreateIngredient(ctx context.Context, ingredientName string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, ingredientName)
	var i Ingredient
	err := row.Scan(&i.IngredientID, &i.IngredientName, &i.UnitID)
	return i, err
}

const createIngredientToCategory = `-- name: CreateIngredientToCategory :exec
insert into ingredients_to_categories (ingredient_id, category_id) values ($1, $2)
`

type CreateIngredientToCategoryParams struct {
	IngredientID int32
	CategoryID   int32
}

func (q *Queries) CreateIngredientToCategory(ctx context.Context, arg CreateIngredientToCategoryParams) error {
	_, err := q.db.Exec(ctx, createIngredientToCategory, arg.IngredientID, arg.CategoryID)
	return err
}

const createList = `-- name: CreateList :one
insert into lists (list_name, user_id) values ($1, $2) returning list_id, list_name, user_id, created_at, updated_at
`

type CreateListParams struct {
	ListName pgtype.Text
	UserID   int32
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.ListName, arg.UserID)
	var i List
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createListToRecipe = `-- name: CreateListToRecipe :one
insert into lists_to_recipes (list_id, recipe_id, list_recipe_quantity) values ($1, $2, $3) returning list_id, recipe_id, list_recipe_quantity
`

type CreateListToRecipeParams struct {
	ListID             int32
	RecipeID           int32
	ListRecipeQuantity float32
}

func (q *Queries) CreateListToRecipe(ctx context.Context, arg CreateListToRecipeParams) (ListsToRecipe, error) {
	row := q.db.QueryRow(ctx, createListToRecipe, arg.ListID, arg.RecipeID, arg.ListRecipeQuantity)
	var i ListsToRecipe
	err := row.Scan(&i.ListID, &i.RecipeID, &i.ListRecipeQuantity)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
insert into recipes (recipe_name, directions, source_url, image_filename) values ($1, $2, $3, $4) returning recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at
`

type CreateRecipeParams struct {
	RecipeName    string
	Directions    string
	SourceUrl     pgtype.Text
	ImageFilename string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.RecipeName,
		arg.Directions,
		arg.SourceUrl,
		arg.ImageFilename,
	)
	var i Recipe
	err := row.Scan(
		&i.RecipeID,
		&i.RecipeName,
		&i.Directions,
		&i.SourceUrl,
		&i.ImageFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeCategory = `-- name: CreateRecipeCategory :one
insert into recipe_categories (recipe_category_name) values ($1) returning recipe_category_id, recipe_category_name
`

func (q *Queries) CreateRecipeCategory(ctx context.Context, recipeCategoryName string) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, createRecipeCategory, recipeCategoryName)
	var i RecipeCategory
	err := row.Scan(&i.RecipeCategoryID, &i.RecipeCategoryName)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (username, password_hash, role) values ($1, $2, $3) returning user_id, username, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Role         Role
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
insert into user_sessions (session_id, user_id, last_access) values ($1, $2, now()) returning session_id, user_id, last_access
`

type CreateUserSessionParams struct {
	SessionID string
	UserID    int32
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.SessionID, arg.UserID)
	var i UserSession
	err := row.Scan(&i.SessionID, &i.UserID, &i.LastAccess)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
delete from ingredients where ingredient_id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, ingredientID int32) error {
	_, err := q.db.Exec(ctx, deleteIngredient, ingredientID)
	return err
}

const deleteRecipeCategory = `-- name: DeleteRecipeCategory :exec
delete from recipe_categories where recipe_category_id = $1
`

func (q *Queries) DeleteRecipeCategory(ctx context.Context, recipeCategoryID int32) error {
	_, err := q.db.Exec(ctx, deleteRecipeCategory, recipeCategoryID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const deleteUserSessionBySessionID = `-- name: DeleteUserSessionBySessionID :exec
delete from user_sessions where session_id = $1
`

func (q *Queries) DeleteUserSessionBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessionBySessionID, sessionID)
	return err
}

const deleteUserSessionByUserID = `-- name: DeleteUserSessionByUserID :exec
delete from user_sessions where user_id = $1
`

func (q *Queries) DeleteUserSessionByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessionByUserID, userID)
	return err
}

const getAllIngredientCategories = `-- name: GetAllIngredientCategories :many
select ingredient_category_id, ingredient_category_name from ingredient_categories
`

func (q *Queries) GetAllIngredientCategories(ctx context.Context) ([]IngredientCategory, error) {
	rows, err := q.db.Query(ctx, getAllIngredientCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientCategory
	for rows.Next() {
		var i IngredientCategory
		if err := rows.Scan(&i.IngredientCategoryID, &i.IngredientCategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIngredients = `-- name: GetAllIngredients :many
select ingredient_id, ingredient_name, unit_id from ingredients
`

func (q *Queries) GetAllIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getAllIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.IngredientID, &i.IngredientName, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllListAssociatedRecipes = `-- name: GetAllListAssociatedRecipes :many
select recipes.recipe_id, recipes.recipe_name, recipes.directions, recipes.source_url, recipes.image_filename, recipes.created_at, recipes.updated_at, lists_to_recipes.list_recipe_quantity from lists_to_recipes
join recipes on lists_to_recipes.recipe_id = recipes.recipe_id
where lists_to_recipes.list_id = $1::int
`

type GetAllListAssociatedRecipesRow struct {
	RecipeID           int32
	RecipeName         string
	Directions         string
	SourceUrl          pgtype.Text
	ImageFilename      string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	ListRecipeQuantity float32
}

func (q *Queries) GetAllListAssociatedRecipes(ctx context.Context, listID int32) ([]GetAllListAssociatedRecipesRow, error) {
	rows, err := q.db.Query(ctx, getAllListAssociatedRecipes, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllListAssociatedRecipesRow
	for rows.Next() {
		var i GetAllListAssociatedRecipesRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.RecipeName,
			&i.Directions,
			&i.SourceUrl,
			&i.ImageFilename,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListRecipeQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRecipeCategories = `-- name: GetAllRecipeCategories :many
select recipe_category_id, recipe_category_name from recipe_categories
`

func (q *Queries) GetAllRecipeCategories(ctx context.Context) ([]RecipeCategory, error) {
	rows, err := q.db.Query(ctx, getAllRecipeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeCategory
	for rows.Next() {
		var i RecipeCategory
		if err := rows.Scan(&i.RecipeCategoryID, &i.RecipeCategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUnits = `-- name: GetAllUnits :many
select unit_id, unit_name, conversion_factor, unit_category from units
`

func (q *Queries) GetAllUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getAllUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitName,
			&i.ConversionFactor,
			&i.UnitCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFreeListItemsAndFullIngredients = `-- name: GetFreeListItemsAndFullIngredients :one
select lists.list_id, list_name, user_id, created_at, updated_at, list_item_id, list_items.list_id, list_items.ingredient_id, list_items.custom_list_item_id, ingredients.ingredient_id, ingredient_name, ingredients.unit_id, units.unit_id, units.unit_name, units.conversion_factor, units.unit_category, custom_list_items.custom_list_item_id, custom_list_item_name, custom_list_item_quantity, custom_unit, custom_list_items.unit_id, units.unit_id, units.unit_name, units.conversion_factor, units.unit_category from lists
join list_items on lists.list_id = free_list_items.list_id
join ingredients on free_list_items.ingredient_id = ingredients.ingredient_id
join units on ingredients.unit_id = units.unit_id
join custom_list_items on free_list_items.custom_list_item_id = custom_list_items.custom_list_item_id
join units on custom_list_items.unit_id = units.unit_id
where lists.list_id = $1
`

type GetFreeListItemsAndFullIngredientsRow struct {
	ListID                 int32
	ListName               pgtype.Text
	UserID                 int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	ListItemID             int32
	ListID_2               int32
	IngredientID           pgtype.Int4
	CustomListItemID       pgtype.Int4
	IngredientID_2         int32
	IngredientName         string
	UnitID                 pgtype.Int4
	UnitID_2               int32
	UnitName               string
	ConversionFactor       float32
	UnitCategory           NullUnitCategory
	CustomListItemID_2     int32
	CustomListItemName     pgtype.Text
	CustomListItemQuantity pgtype.Float4
	CustomUnit             pgtype.Text
	UnitID_3               pgtype.Int4
	UnitID_4               int32
	UnitName_2             string
	ConversionFactor_2     float32
	UnitCategory_2         NullUnitCategory
}

func (q *Queries) GetFreeListItemsAndFullIngredients(ctx context.Context, listID int32) (GetFreeListItemsAndFullIngredientsRow, error) {
	row := q.db.QueryRow(ctx, getFreeListItemsAndFullIngredients, listID)
	var i GetFreeListItemsAndFullIngredientsRow
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListItemID,
		&i.ListID_2,
		&i.IngredientID,
		&i.CustomListItemID,
		&i.IngredientID_2,
		&i.IngredientName,
		&i.UnitID,
		&i.UnitID_2,
		&i.UnitName,
		&i.ConversionFactor,
		&i.UnitCategory,
		&i.CustomListItemID_2,
		&i.CustomListItemName,
		&i.CustomListItemQuantity,
		&i.CustomUnit,
		&i.UnitID_3,
		&i.UnitID_4,
		&i.UnitName_2,
		&i.ConversionFactor_2,
		&i.UnitCategory_2,
	)
	return i, err
}

const getIngredientAssociatedCategories = `-- name: GetIngredientAssociatedCategories :many
select ingredient_categories.ingredient_category_id, ingredient_categories.ingredient_category_name from ingredients_to_categories
join ingredient_categories on ingredients_to_categories.category_id = ingredient_categories.ingredient_category_id
where ingredients_to_categories.ingredient_id = $1
`

func (q *Queries) GetIngredientAssociatedCategories(ctx context.Context, ingredientID int32) ([]IngredientCategory, error) {
	rows, err := q.db.Query(ctx, getIngredientAssociatedCategories, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientCategory
	for rows.Next() {
		var i IngredientCategory
		if err := rows.Scan(&i.IngredientCategoryID, &i.IngredientCategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientByID = `-- name: GetIngredientByID :one
select ingredient_id, ingredient_name, unit_id from ingredients where ingredient_id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, ingredientID int32) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, ingredientID)
	var i Ingredient
	err := row.Scan(&i.IngredientID, &i.IngredientName, &i.UnitID)
	return i, err
}

const getIngredientsWithOffset = `-- name: GetIngredientsWithOffset :many
select ingredient_id, ingredient_name, unit_id from ingredients offset $1 limit $2
`

type GetIngredientsWithOffsetParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetIngredientsWithOffset(ctx context.Context, arg GetIngredientsWithOffsetParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredientsWithOffset, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.IngredientID, &i.IngredientName, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListAssociatedRecipeByID = `-- name: GetListAssociatedRecipeByID :one
select recipes.recipe_id, recipes.recipe_name, recipes.directions, recipes.source_url, recipes.image_filename, recipes.created_at, recipes.updated_at from lists_to_recipes
join recipes on lists_to_recipes.recipe_id = recipes.recipe_id
where lists_to_recipes.list_id = $1::int and recipes.recipe_id = $2::int
`

type GetListAssociatedRecipeByIDParams struct {
	ListID   int32
	RecipeID int32
}

func (q *Queries) GetListAssociatedRecipeByID(ctx context.Context, arg GetListAssociatedRecipeByIDParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getListAssociatedRecipeByID, arg.ListID, arg.RecipeID)
	var i Recipe
	err := row.Scan(
		&i.RecipeID,
		&i.RecipeName,
		&i.Directions,
		&i.SourceUrl,
		&i.ImageFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListAssociatedRecipesAndQuantities = `-- name: GetListAssociatedRecipesAndQuantities :many
select list_id, lists_to_recipes.recipe_id, list_recipe_quantity, recipes.recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at from lists_to_recipes
join recipes on lists_to_recipes.recipe_id = recipes.recipe_id
where lists_to_recipes.list_id = $1
`

type GetListAssociatedRecipesAndQuantitiesRow struct {
	ListID             int32
	RecipeID           int32
	ListRecipeQuantity float32
	RecipeID_2         int32
	RecipeName         string
	Directions         string
	SourceUrl          pgtype.Text
	ImageFilename      string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) GetListAssociatedRecipesAndQuantities(ctx context.Context, listID int32) ([]GetListAssociatedRecipesAndQuantitiesRow, error) {
	rows, err := q.db.Query(ctx, getListAssociatedRecipesAndQuantities, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListAssociatedRecipesAndQuantitiesRow
	for rows.Next() {
		var i GetListAssociatedRecipesAndQuantitiesRow
		if err := rows.Scan(
			&i.ListID,
			&i.RecipeID,
			&i.ListRecipeQuantity,
			&i.RecipeID_2,
			&i.RecipeName,
			&i.Directions,
			&i.SourceUrl,
			&i.ImageFilename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListByID = `-- name: GetListByID :one
select list_id, list_name, user_id, created_at, updated_at from lists where list_id = $1
`

func (q *Queries) GetListByID(ctx context.Context, listID int32) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, listID)
	var i List
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListByName = `-- name: GetListByName :one
select list_id, list_name, user_id, created_at, updated_at from lists where list_name = $1
`

func (q *Queries) GetListByName(ctx context.Context, listName pgtype.Text) (List, error) {
	row := q.db.QueryRow(ctx, getListByName, listName)
	var i List
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListLeftJoinListToRecipe = `-- name: GetListLeftJoinListToRecipe :one
select lists.list_id, lists.list_name, lists.user_id, lists.created_at, lists.updated_at, lists_to_recipes.list_recipe_quantity from lists
left join lists_to_recipes on lists.list_id = lists_to_recipes.list_id
where lists.list_id = $1::int and lists_to_recipes.recipe_id = $2::int
`

type GetListLeftJoinListToRecipeParams struct {
	ListID   int32
	RecipeID int32
}

type GetListLeftJoinListToRecipeRow struct {
	ListID             int32
	ListName           pgtype.Text
	UserID             int32
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	ListRecipeQuantity pgtype.Float4
}

func (q *Queries) GetListLeftJoinListToRecipe(ctx context.Context, arg GetListLeftJoinListToRecipeParams) (GetListLeftJoinListToRecipeRow, error) {
	row := q.db.QueryRow(ctx, getListLeftJoinListToRecipe, arg.ListID, arg.RecipeID)
	var i GetListLeftJoinListToRecipeRow
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListRecipeQuantity,
	)
	return i, err
}

const getListRecipesAndFullRecipeIngredients = `-- name: GetListRecipesAndFullRecipeIngredients :one
select lists.list_id, list_name, user_id, lists.created_at, lists.updated_at, lists_to_recipes.list_id, lists_to_recipes.recipe_id, list_recipe_quantity, recipes.recipe_id, recipe_name, directions, source_url, image_filename, recipes.created_at, recipes.updated_at, recipes_to_ingredients.recipe_id, recipes_to_ingredients.ingredient_id, recipe_ingredient_quantity, ingredients.ingredient_id, ingredient_name, ingredients.unit_id, units.unit_id, unit_name, conversion_factor, unit_category from lists
join lists_to_recipes on lists.list_id = lists_to_recipes.list_id
join recipes on lists_to_recipes.recipe_id = recipes.recipe_id
join recipes_to_ingredients on recipes.recipe_id = recipes_to_ingredients.recipe_id
join ingredients on recipes_to_ingredients.ingredient_id = ingredients.ingredient_id
join units on ingredients.unit_id = units.unit_id
where lists.list_id = $1
`

type GetListRecipesAndFullRecipeIngredientsRow struct {
	ListID                   int32
	ListName                 pgtype.Text
	UserID                   int32
	CreatedAt                pgtype.Timestamp
	UpdatedAt                pgtype.Timestamp
	ListID_2                 int32
	RecipeID                 int32
	ListRecipeQuantity       float32
	RecipeID_2               int32
	RecipeName               string
	Directions               string
	SourceUrl                pgtype.Text
	ImageFilename            string
	CreatedAt_2              pgtype.Timestamp
	UpdatedAt_2              pgtype.Timestamp
	RecipeID_3               int32
	IngredientID             int32
	RecipeIngredientQuantity float32
	IngredientID_2           int32
	IngredientName           string
	UnitID                   pgtype.Int4
	UnitID_2                 int32
	UnitName                 string
	ConversionFactor         float32
	UnitCategory             NullUnitCategory
}

func (q *Queries) GetListRecipesAndFullRecipeIngredients(ctx context.Context, listID int32) (GetListRecipesAndFullRecipeIngredientsRow, error) {
	row := q.db.QueryRow(ctx, getListRecipesAndFullRecipeIngredients, listID)
	var i GetListRecipesAndFullRecipeIngredientsRow
	err := row.Scan(
		&i.ListID,
		&i.ListName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListID_2,
		&i.RecipeID,
		&i.ListRecipeQuantity,
		&i.RecipeID_2,
		&i.RecipeName,
		&i.Directions,
		&i.SourceUrl,
		&i.ImageFilename,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.RecipeID_3,
		&i.IngredientID,
		&i.RecipeIngredientQuantity,
		&i.IngredientID_2,
		&i.IngredientName,
		&i.UnitID,
		&i.UnitID_2,
		&i.UnitName,
		&i.ConversionFactor,
		&i.UnitCategory,
	)
	return i, err
}

const getListsByUserID = `-- name: GetListsByUserID :many
select list_id, list_name, user_id, created_at, updated_at from lists where user_id = $1
`

func (q *Queries) GetListsByUserID(ctx context.Context, userID int32) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ListID,
			&i.ListName,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeAndAssociatedData = `-- name: GetRecipeAndAssociatedData :one
select recipes.recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at, recipe_to_recipe_category_id, recipes_to_recipe_categories.recipe_id, recipes_to_recipe_categories.recipe_category_id, recipe_categories.recipe_category_id, recipe_category_name, recipes_to_ingredients.recipe_id, recipes_to_ingredients.ingredient_id, recipe_ingredient_quantity, ingredients.ingredient_id, ingredient_name, ingredients.unit_id, units.unit_id, unit_name, conversion_factor, unit_category from recipes
join recipes_to_recipe_categories on recipes.recipe_id = recipes_to_recipe_categories.recipe_id
join recipe_categories on recipes_to_recipe_categories.recipe_category_id = recipe_categories.recipe_category_id
join recipes_to_ingredients on recipes.recipe_id = recipes_to_ingredients.recipe_id
join ingredients on recipes_to_ingredients.ingredient_id = ingredients.ingredient_id
join units on ingredients.unit_id = units.unit_id
where recipes.recipe_id = $1
`

type GetRecipeAndAssociatedDataRow struct {
	RecipeID                 int32
	RecipeName               string
	Directions               string
	SourceUrl                pgtype.Text
	ImageFilename            string
	CreatedAt                pgtype.Timestamp
	UpdatedAt                pgtype.Timestamp
	RecipeToRecipeCategoryID int32
	RecipeID_2               int32
	RecipeCategoryID         int32
	RecipeCategoryID_2       int32
	RecipeCategoryName       string
	RecipeID_3               int32
	IngredientID             int32
	RecipeIngredientQuantity float32
	IngredientID_2           int32
	IngredientName           string
	UnitID                   pgtype.Int4
	UnitID_2                 int32
	UnitName                 string
	ConversionFactor         float32
	UnitCategory             NullUnitCategory
}

func (q *Queries) GetRecipeAndAssociatedData(ctx context.Context, recipeID int32) (GetRecipeAndAssociatedDataRow, error) {
	row := q.db.QueryRow(ctx, getRecipeAndAssociatedData, recipeID)
	var i GetRecipeAndAssociatedDataRow
	err := row.Scan(
		&i.RecipeID,
		&i.RecipeName,
		&i.Directions,
		&i.SourceUrl,
		&i.ImageFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipeToRecipeCategoryID,
		&i.RecipeID_2,
		&i.RecipeCategoryID,
		&i.RecipeCategoryID_2,
		&i.RecipeCategoryName,
		&i.RecipeID_3,
		&i.IngredientID,
		&i.RecipeIngredientQuantity,
		&i.IngredientID_2,
		&i.IngredientName,
		&i.UnitID,
		&i.UnitID_2,
		&i.UnitName,
		&i.ConversionFactor,
		&i.UnitCategory,
	)
	return i, err
}

const getRecipeAssociatedCategories = `-- name: GetRecipeAssociatedCategories :many
select recipe_categories.recipe_category_id, recipe_categories.recipe_category_name from recipe_categories
join recipes_to_recipe_categories on recipe_categories.recipe_category_id = recipes_to_recipe_categories.recipe_category_id
where recipes_to_recipe_categories.recipe_id = $1
`

func (q *Queries) GetRecipeAssociatedCategories(ctx context.Context, recipeID int32) ([]RecipeCategory, error) {
	rows, err := q.db.Query(ctx, getRecipeAssociatedCategories, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeCategory
	for rows.Next() {
		var i RecipeCategory
		if err := rows.Scan(&i.RecipeCategoryID, &i.RecipeCategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeAssociatedIngredientsAndUnits = `-- name: GetRecipeAssociatedIngredientsAndUnits :many
select ingredients.ingredient_id, ingredient_name, ingredients.unit_id, recipe_id, recipes_to_ingredients.ingredient_id, recipe_ingredient_quantity, units.unit_id, unit_name, conversion_factor, unit_category from ingredients
join recipes_to_ingredients on ingredients.ingredient_id = recipes_to_ingredients.ingredient_id
join units on ingredients.unit_id = units.unit_id
where recipes_to_ingredients.recipe_id = $1
`

type GetRecipeAssociatedIngredientsAndUnitsRow struct {
	IngredientID             int32
	IngredientName           string
	UnitID                   pgtype.Int4
	RecipeID                 int32
	IngredientID_2           int32
	RecipeIngredientQuantity float32
	UnitID_2                 int32
	UnitName                 string
	ConversionFactor         float32
	UnitCategory             NullUnitCategory
}

func (q *Queries) GetRecipeAssociatedIngredientsAndUnits(ctx context.Context, recipeID int32) ([]GetRecipeAssociatedIngredientsAndUnitsRow, error) {
	rows, err := q.db.Query(ctx, getRecipeAssociatedIngredientsAndUnits, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeAssociatedIngredientsAndUnitsRow
	for rows.Next() {
		var i GetRecipeAssociatedIngredientsAndUnitsRow
		if err := rows.Scan(
			&i.IngredientID,
			&i.IngredientName,
			&i.UnitID,
			&i.RecipeID,
			&i.IngredientID_2,
			&i.RecipeIngredientQuantity,
			&i.UnitID_2,
			&i.UnitName,
			&i.ConversionFactor,
			&i.UnitCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeByID = `-- name: GetRecipeByID :one
select recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at from recipes where recipe_id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, recipeID int32) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, recipeID)
	var i Recipe
	err := row.Scan(
		&i.RecipeID,
		&i.RecipeName,
		&i.Directions,
		&i.SourceUrl,
		&i.ImageFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipesByNameAndCategoryID = `-- name: GetRecipesByNameAndCategoryID :many
select recipe_to_recipe_category_id, recipes_to_recipe_categories.recipe_id, recipe_category_id, recipes.recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at from recipes_to_recipe_categories
join recipes on recipes_to_recipe_categories.recipe_id = recipes.recipe_id
where recipes.recipe_name = $1 and recipes_to_recipe_categories.recipe_category_id = $2
`

type GetRecipesByNameAndCategoryIDParams struct {
	RecipeName       string
	RecipeCategoryID int32
}

type GetRecipesByNameAndCategoryIDRow struct {
	RecipeToRecipeCategoryID int32
	RecipeID                 int32
	RecipeCategoryID         int32
	RecipeID_2               int32
	RecipeName               string
	Directions               string
	SourceUrl                pgtype.Text
	ImageFilename            string
	CreatedAt                pgtype.Timestamp
	UpdatedAt                pgtype.Timestamp
}

func (q *Queries) GetRecipesByNameAndCategoryID(ctx context.Context, arg GetRecipesByNameAndCategoryIDParams) ([]GetRecipesByNameAndCategoryIDRow, error) {
	rows, err := q.db.Query(ctx, getRecipesByNameAndCategoryID, arg.RecipeName, arg.RecipeCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesByNameAndCategoryIDRow
	for rows.Next() {
		var i GetRecipesByNameAndCategoryIDRow
		if err := rows.Scan(
			&i.RecipeToRecipeCategoryID,
			&i.RecipeID,
			&i.RecipeCategoryID,
			&i.RecipeID_2,
			&i.RecipeName,
			&i.Directions,
			&i.SourceUrl,
			&i.ImageFilename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipesWithOffset = `-- name: GetRecipesWithOffset :many
select recipe_id, recipe_name, directions, source_url, image_filename, created_at, updated_at from recipes offset $1 limit $2
`

type GetRecipesWithOffsetParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetRecipesWithOffset(ctx context.Context, arg GetRecipesWithOffsetParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, getRecipesWithOffset, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.RecipeID,
			&i.RecipeName,
			&i.Directions,
			&i.SourceUrl,
			&i.ImageFilename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
select unit_id, unit_name, conversion_factor, unit_category from units where unit_id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, unitID int32) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, unitID)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.ConversionFactor,
		&i.UnitCategory,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select user_id, username, password_hash, role, created_at, updated_at from users where user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select user_id, username, password_hash, role, created_at, updated_at from users where username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionBySessionID = `-- name: GetUserSessionBySessionID :one
select session_id, user_id, last_access from user_sessions where session_id = $1
`

func (q *Queries) GetUserSessionBySessionID(ctx context.Context, sessionID string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionBySessionID, sessionID)
	var i UserSession
	err := row.Scan(&i.SessionID, &i.UserID, &i.LastAccess)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
update ingredients set ingredient_name = $2 where ingredient_id = $1 returning ingredient_id, ingredient_name, unit_id
`

type UpdateIngredientParams struct {
	IngredientID   int32
	IngredientName string
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient, arg.IngredientID, arg.IngredientName)
	var i Ingredient
	err := row.Scan(&i.IngredientID, &i.IngredientName, &i.UnitID)
	return i, err
}

const updateListToRecipeQuantity = `-- name: UpdateListToRecipeQuantity :exec
update lists_to_recipes set list_recipe_quantity = $3 where list_id = $1 and recipe_id = $2
`

type UpdateListToRecipeQuantityParams struct {
	ListID             int32
	RecipeID           int32
	ListRecipeQuantity float32
}

func (q *Queries) UpdateListToRecipeQuantity(ctx context.Context, arg UpdateListToRecipeQuantityParams) error {
	_, err := q.db.Exec(ctx, updateListToRecipeQuantity, arg.ListID, arg.RecipeID, arg.ListRecipeQuantity)
	return err
}

const updateRecipeCategory = `-- name: UpdateRecipeCategory :one
update recipe_categories set recipe_category_name = $2 where recipe_category_id = $1 returning recipe_category_id, recipe_category_name
`

type UpdateRecipeCategoryParams struct {
	RecipeCategoryID   int32
	RecipeCategoryName string
}

func (q *Queries) UpdateRecipeCategory(ctx context.Context, arg UpdateRecipeCategoryParams) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, updateRecipeCategory, arg.RecipeCategoryID, arg.RecipeCategoryName)
	var i RecipeCategory
	err := row.Scan(&i.RecipeCategoryID, &i.RecipeCategoryName)
	return i, err
}
