// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed.sql

package sqlc

import (
	"context"
)

const seedDatabase = `-- name: SeedDatabase :exec
do $$
begin
    call seed_db();
end
$$ language plpgsql
`

func (q *Queries) SeedDatabase(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedDatabase)
	return err
}
